spring:
  config:
    activate:
      on-profile: prod

build:
  version: "0.3"

cards:
  message: "Welcome to iBank Cards Service (Prod env)!"
  contactDetails:
    name: "Arman Iqbal - Developer"
    email: "armaniqbal@gmail.com"
  onCallSupport:
    - "armaniqbal@gmail.com"