name: "ibank-backend"

services:
  accounts:
    image: "thekotik/accounts:0.1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 700M
    networks:
      - ibank

  loans:
    image: "thekotik/loans:0.1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 700M
    networks:
      - ibank

  cards:
    image: "thekotik/cards:0.1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 700M
    networks:
      - ibank

networks:
  ibank:
    driver: bridge
    