services:
  network-deploy-service:
    networks:
      - ibank

  # Base microservice config
  microservice-base-config:
    extends:
      service: network-deploy-service
    resources:
      limits:
        memory: 700M
    environment:
      SPRING_RABBITMQ_HOST: rabbit

  # Config-server config
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/