spring:
  config:
    activate:
      on-profile: prod

build:
  version: "0.3"

accounts:
  message: "Welcome to iBank Accounts Service (Prod env)!"
  contactDetails:
    name: "Arman Iqbal - Developer"
    email: "armaniqbal@gmail.com"
  onCallSupport:
    - "armaniqbal@gmail.com"